<!-- Dashboard panel -->
<div class="dashboard-panel">

	<div class="download-report"><a href="#"><i class="fa  fa-download"></i> &nbsp;Download Report</a></div>
	<div class="table-responsive">
	   <table class="report-table row-border ">
		<thead>
			<tr>
				<th>Date</th>
				<th>Transaction ID</th>
				<th>Amount</th>
				<th>Via</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>20/11/2015</td>
				<td>SADJKANKDN151</td>
				<td>$30.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>21/11/2015</td>
				<td>SADJKANKDN152</td>
				<td>$34.5</td>
				<td>Payzip</td>
			</tr>
			<tr>
				<td>22/11/2015</td>
				<td>SADJKANKDN153</td>
				<td>$38.5</td>
				<td>Paytm</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
			<tr>
				<td>23/11/2015</td>
				<td>SADJKANKDN154</td>
				<td>$40.5</td>
				<td>Paypal</td>
			</tr>
		</tbody>
	</table>
</div>
</div>